### ISSUE TITLE
[Bug] SmartEdit feature no longer available for undocumented entities.

### ISSUE THREAD

**Issue by GeeNoVoid** [ficool2/HammerPlusPlus-Issue-Tracker#14]
Hidden entities that were unhidden with an fgd no longer work with smart edit, and trying to edit trigger_add_or_remove_tf_player_attributes in particular shortens the entity name to trigger_add_or_remove_tf_player.
![image](https://user-images.githubusercontent.com/9409518/150620522-9b91bc9b-78d9-4da7-b236-a0c529b548a4.png)
Build: 8853
Game: TF2

**Comment by ficool2** [comment]
It looks like you aren't mounting the correct FGD files in the game configuration, check that you have the correct ones added

**Comment by SpookyToad2** [comment]
https://user-images.githubusercontent.com/74873411/150643855-06386b53-e357-4212-ba84-6be5db2b9e3c.mp4

Seems like it's just removing _attributes line and leaves it as trigger_add_or_remove_tf_player

**Comment by ficool2** [comment]
Fixed in build 8854

**Comment by GeeNoVoid** [comment]
Looks like it's still happening in the newest version.

https://user-images.githubusercontent.com/9409518/150654240-faf5f2b3-838c-4d04-9487-ebefc68f0e0a.mp4

**Comment by GeeNoVoid** [comment]
ok it's working in the newest build thx :)
