### ISSUE TITLE
[Bug, Unknown Build, TF2 and CS:GO] Hammer++ Creates Weird Useless Folders

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#212]
H++ seems to be creating random empty folders in whatever folder it's in, with some extremely weird names. not just keyboard mashing, more like insert-special-character mashing. deleting them doesn't seem to cause any issues.
example from `Counter-Strike Global Offensive/bin`: 
![image](https://user-images.githubusercontent.com/97305860/154158162-4b049c6a-ad09-40ef-94af-c6fc0f9de612.png)

**Comment by ficool2** [comment]
This might have been fixed in latest build already, I'll reopen if thats not the case

**Comment by GXP10** [comment]
> This might have been fixed in latest build already, I'll reopen if thats not the case

actually this is still happened
![preview](https://user-images.githubusercontent.com/55353008/154852465-f744ea67-aa78-43eb-8dac-3d3d79a0c087.png)
and yes this is the recent one
