### ISSUE TITLE
CS:GO Hammer++ (8860) no longer working on the latest CS:GO SDK update

### ISSUE THREAD

**Issue by Shadowysn** [ficool2/HammerPlusPlus-Issue-Tracker#354]
_can cs:go stop fucking over the modding community_

Hammer++ no longer works on the latest CS:GO SDK.
No window or icon to indicate activity shows, nor does an error pop up.
_hammerplusplus.exe_ appears in Task Manager for a short time before closing.

**Comment by thetomix7** [comment]
Same thing here, i wasted like an 1.5 hours trying to fix this.

**Comment by laot7490** [comment]
This should be fixed

**Comment by HolzstockG** [comment]
Same shit. Doesn't work. It shows on steam CSGO SDK running for like 10 seconds and goes again online. Pls fix

**Comment by AutoJumper** [comment]
Still happening. I checked in process hacker and a second after hammer++ is launched it just shuts down.

**Comment by roembol2000** [comment]
Same here, but the author doesn't really seem to be active on the issue tracker. It looks like the last time they replied to an issue was back in February...

**Comment by ficool2** [comment]
Fixed under build 8861
